import type{Lesson}from'../lessons/types';
export type VocabularyDifficulty='everyday'|'introduced'|'academic';
export interface VocabularyIntroduction{word:string;explanation:string}
export interface ReadingLevelProfile{targetReadingBand:'early-reader'|'developing-reader'|'transitional-reader'|'fluent-reader';targetGradeRange:string;targetSkill:string;maximumVocabularyDifficulty:VocabularyDifficulty;averageSentenceLength:number;maximumSentenceLength:number;unfamiliarWordsAllowed:number;unfamiliarWords:VocabularyIntroduction[];unfamiliarWordsPreTaught:boolean}
export type CurriculumWarningCode='average-sentence-length'|'maximum-sentence-length'|'too-many-unfamiliar-words'|'unprepared-vocabulary'|'academic-vocabulary'|'outside-knowledge'|'unsupported-answer'|'multiple-primary-skills';
export interface CurriculumWarning{lessonId:string;code:CurriculumWarningCode;message:string}
const academicWords=new Set(['variable','trials','engineer','repeated','hypothesis','analyze','consequently','methodology','physically','transforms','recovered']);
export const words=(text:string)=>text.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g)??[];
export const sentenceLengths=(text:string)=>(text.match(/[^.!?]+[.!?]+/g)??[text]).map(sentence=>words(sentence).length);
export function readingLevel(text:string,targetSkill:string,unfamiliarWords:VocabularyIntroduction[]=[]):ReadingLevelProfile{const lengths=sentenceLengths(text);return{targetReadingBand:'early-reader',targetGradeRange:'K–2',targetSkill,maximumVocabularyDifficulty:'introduced',averageSentenceLength:Number((lengths.reduce((a,b)=>a+b,0)/lengths.length).toFixed(1)),maximumSentenceLength:Math.max(...lengths),unfamiliarWordsAllowed:2,unfamiliarWords,unfamiliarWordsPreTaught:unfamiliarWords.length>0}}
export function validateLessonCurriculum(lesson:Lesson):CurriculumWarning[]{const warnings:CurriculumWarning[]=[];const profile=lesson.readingLevel,lengths=sentenceLengths(lesson.passage),actualAverage=lengths.reduce((a,b)=>a+b,0)/lengths.length,actualMax=Math.max(...lengths);const warn=(code:CurriculumWarningCode,message:string)=>warnings.push({lessonId:lesson.id,code,message});if(actualAverage>profile.averageSentenceLength+.5)warn('average-sentence-length',`Average sentence length is ${actualAverage.toFixed(1)} words.`);if(actualMax>profile.maximumSentenceLength)warn('maximum-sentence-length',`A sentence has ${actualMax} words.`);if(profile.unfamiliarWords.length>profile.unfamiliarWordsAllowed)warn('too-many-unfamiliar-words','The passage declares too many unfamiliar words.');if(profile.unfamiliarWords.length&&!profile.unfamiliarWordsPreTaught)warn('unprepared-vocabulary','New words must be pre-taught.');const unfamiliar=new Set(profile.unfamiliarWords.map(x=>x.word));const unapprovedAcademic=words(lesson.passage).filter(word=>academicWords.has(word)&&!unfamiliar.has(word));if(unapprovedAcademic.length)warn('academic-vocabulary',`Unnecessary academic vocabulary: ${[...new Set(unapprovedAcademic)].join(', ')}.`);if(new Set(lesson.activities.map(a=>a.targetSkill)).size!==1)warn('multiple-primary-skills','Activities do not share one scored mission skill.');for(const activity of lesson.activities){if(activity.requiresOutsideKnowledge)warn('outside-knowledge',`${activity.id} requires knowledge beyond the passage or scene.`);if(activity.answer!==undefined&&activity.evidenceText&&!lesson.passage.toLowerCase().includes(activity.evidenceText.toLowerCase()))warn('unsupported-answer',`${activity.id} lacks direct passage evidence.`)}return warnings}
export const validateCurriculum=(lessons:Lesson[])=>lessons.flatMap(validateLessonCurriculum);
