import{useEffect,useRef,useState}from'react';import type{PlayerProfile}from'../../profiles/types';import{dialogueFor}from'../data/dialogue';import{addFriendship,emptyRelationship,requestNpcHelp}from'../engine/npcEngine';import type{DialogueSituation,NpcDefinition}from'../types';import{npcVoiceService}from'../voice/voiceService';import{NpcCharacter}from'./NpcCharacter';
export function NpcDialogue({npc,player,situation='first-meeting',activityId,skill,onSave}:{npc:NpcDefinition;player:PlayerProfile;situation?:DialogueSituation;activityId?:string;skill?:string;onSave?:(p:PlayerProfile)=>void}){
 const[caption,setCaption]=useState(dialogueFor(npc.id,situation,player.firstName)),[speaking,setSpeaking]=useState(false),[hintLevel,setHintLevel]=useState(0),[gift,setGift]=useState<string>();const mounted=useRef(true),relationship=player.npcRelationships?.[npc.id]??emptyRelationship(npc.id,player.id);useEffect(()=>()=>{mounted.current=false;npcVoiceService.stop()},[]);
 function speak(text=caption){setCaption(text);if(player.parentSettings?.masterMute)return;npcVoiceService.speak(npc,text,player.parentSettings?.voiceVolume??.8,{onStart:()=>mounted.current&&setSpeaking(true),onEnd:()=>mounted.current&&setSpeaking(false)})}
 function ask(){if(!activityId||!skill)return;const next=requestNpcHelp(player,npc,activityId,skill,hintLevel);setHintLevel(next.hint.level);setCaption(next.hint.text);onSave?.(next.player);speak(next.hint.text)}
 function sideQuest(){const id=`${npc.id}-first-side-quest`,updated=addFriendship(relationship,8,{sideQuestId:id,skill:String(npc.skillSpecialties[0]),accomplishment:'Helped with a friendship side quest'});onSave?.({...player,npcRelationships:{...player.npcRelationships,[npc.id]:updated}});setCaption(`${player.firstName}, thank you for helping with my small reading job. Our friendship grew.`)}
 const unlockedGift=relationship.unlockedGiftIds.find(x=>!player.inventory.includes(x));
 return <section className="npc-dialogue" aria-label={`${npc.displayName} dialogue`}><NpcCharacter npc={npc} state={speaking?'talk':hintLevel?'point':'wave'} reduceMotion={player.accessibility.reduceMotion}/><div className="npc-speech"><strong>{npc.displayName}</strong><p className="npc-caption" aria-live="polite">{caption}</p><div className="npc-controls"><button onClick={()=>speak()}>Talk</button><button onClick={()=>speak()}>Replay speech</button>{activityId&&<button className="primary ask-help" onClick={ask}>Ask for Help</button>}<button onClick={()=>setCaption(dialogueFor(npc.id,'returning-player',player.firstName))}>Can you help me?</button><button onClick={()=>setCaption('I’ll be here when you are ready.')}>Maybe later</button></div>{activityId&&<p className="hint-level">Hint level {hintLevel} of 4 · You can ask as often as you need.</p>}{relationship.friendshipLevel>=3&&!relationship.sideQuestsCompleted.includes(`${npc.id}-first-side-quest`)&&<aside className="side-quest-panel"><h3>Friendship side quest</h3><p>Read the name on my work basket and help me place it by the matching sign.</p><button onClick={sideQuest}>Complete small reading side quest</button></aside>}{unlockedGift&&<button onClick={()=>{onSave?.({...player,inventory:[...player.inventory,unlockedGift]});setGift(unlockedGift)}}>Receive friendship gift</button>}{gift&&<div className="gift-received" role="status"><strong>Gift received:</strong> {gift.replaceAll('-',' ')}</div>}<div className="friendship-meter" role="meter" aria-label={`Friendship with ${npc.displayName}`} aria-valuemin={1} aria-valuemax={5} aria-valuenow={relationship.friendshipLevel}><span style={{width:`${relationship.friendshipLevel*20}%`}}/></div><small>Friendship level {relationship.friendshipLevel}</small></div></section>
}
