import type{PlayerProfile}from'../../profiles/types';import{npcById}from'../data/npcs';import type{NpcDefinition,NpcHelpEvent,NpcRelationship,NpcRoutineState}from'../types';
const specialistRules:Array<[RegExp,string]>=[[/evidence|main idea|comprehension/,'hazel'],[/vocabulary|word meaning|high-frequency|color-restoration|matching/,'poppy'],[/sequenc|story order|reading short sentences|story-card/,'finn'],[/oral|fluency|punctuation|read-aloud/,'grandma-buttercup'],[/recipe|sentence building|short vowels|recipe-drop|stirring/,'baker-ben'],[/region restoration|checkpoint|villain|treasure/,'mayor-maple'],[/./,'chef-cinnamon']];
export const specialistForSkill=(skill:string,activityType='')=>npcById(specialistRules.find(([pattern])=>pattern.test(`${skill} ${activityType}`.toLowerCase()))![1]);
export const emptyRelationship=(npcId:string,playerId:string):NpcRelationship=>({npcId,playerId,friendshipLevel:1,friendshipPoints:0,missionsCompletedTogether:0,unlockedDialogueIds:[],unlockedGiftIds:[],sideQuestsCompleted:[]});
export const friendshipLevelForPoints=(points:number)=>Math.min(5,Math.floor(points/25)+1);
export function addFriendship(relationship:NpcRelationship,points:number,options:{mission?:boolean;skill?:string;accomplishment?:string;sideQuestId?:string;now?:Date}={}):NpcRelationship{const total=relationship.friendshipPoints+Math.max(0,points),level=friendshipLevelForPoints(total),npc=npcById(relationship.npcId),rewards=npc.friendshipRewards.filter(x=>x.level<=level);return{...relationship,friendshipPoints:total,friendshipLevel:level,missionsCompletedTogether:relationship.missionsCompletedTogether+(options.mission?1:0),lastInteractionAt:(options.now??new Date()).toISOString(),recentSkill:options.skill??relationship.recentSkill,recentAccomplishment:options.accomplishment??relationship.recentAccomplishment,unlockedDialogueIds:[...new Set([...relationship.unlockedDialogueIds,...rewards.flatMap(x=>x.dialogueId?[x.dialogueId]:[])])],unlockedGiftIds:[...new Set([...relationship.unlockedGiftIds,...rewards.flatMap(x=>x.giftId?[x.giftId]:[])])],sideQuestsCompleted:options.sideQuestId?[...new Set([...relationship.sideQuestsCompleted,options.sideQuestId])]:relationship.sideQuestsCompleted}}
export function nextHint(npc:NpcDefinition,skill:string,currentLevel:number){const rule=npc.helpRules.find(x=>x.skills.some(s=>skill.toLowerCase().includes(s.toLowerCase())||s.toLowerCase().includes(skill.toLowerCase())))??npc.helpRules[0],level=Math.min(4,currentLevel+1);return{level,text:rule.hints[level-1],guided:level>=3}}
export function routineAt(npc:NpcDefinition,date=new Date()):NpcRoutineState{const hour=Number.isFinite(date.getHours())?date.getHours():12,entry=npc.dailyRoutine.find(x=>hour>=x.startHour&&hour<x.endHour)??npc.dailyRoutine[1];return{npcId:npc.id,period:entry.period,location:entry.location,activity:entry.activity,animation:entry.animation,offlineSafe:true}}
export function requestNpcHelp(player:PlayerProfile,npc:NpcDefinition,activityId:string,skill:string,currentLevel:number,now=new Date()){const hint=nextHint(npc,skill,currentLevel),event:NpcHelpEvent={id:crypto.randomUUID(),npcId:npc.id,playerId:player.id,activityId,skill,hintLevel:hint.level,requestedAt:now.toISOString(),guided:hint.guided},relationship=addFriendship(player.npcRelationships?.[npc.id]??emptyRelationship(npc.id,player.id),2,{skill,now});return{hint,event,player:{...player,npcHelpHistory:[...(player.npcHelpHistory??[]),event],npcRelationships:{...player.npcRelationships,[npc.id]:relationship}}}}
export function completeNpcActivity(player:PlayerProfile,npc:NpcDefinition,activityId:string,skill:string,missionComplete=false){const history=[...(player.npcHelpHistory??[])];let index=-1;for(let i=history.length-1;i>=0;i--)if(history[i].activityId===activityId&&history[i].npcId===npc.id&&history[i].succeededAfterward===undefined){index=i;break}if(index>=0)history[index]={...history[index],succeededAfterward:true};const relationship=addFriendship(player.npcRelationships?.[npc.id]??emptyRelationship(npc.id,player.id),missionComplete?10:3,{mission:missionComplete,skill,accomplishment:missionComplete?'Completed a reading mission together':'Used a story clue'});return{...player,npcHelpHistory:history,npcRelationships:{...player.npcRelationships,[npc.id]:relationship}}}
export function summarizeHelp(events:NpcHelpEvent[]){if(!events.length)return{mostUsedHelper:'No helper used yet',typicalHintLevel:0,guidedSuccesses:0,independentSuccesses:0,skills:[]as string[]};const counts=new Map<string,number>();for(const e of events)counts.set(e.npcId,(counts.get(e.npcId)??0)+1);const most=[...counts].sort((a,b)=>b[1]-a[1])[0][0];return{mostUsedHelper:npcById(most).displayName,typicalHintLevel:Math.round(events.reduce((n,e)=>n+e.hintLevel,0)/events.length),guidedSuccesses:events.filter(e=>e.guided&&e.succeededAfterward).length,independentSuccesses:events.filter(e=>!e.guided&&e.succeededAfterward).length,skills:[...new Set(events.map(e=>e.skill))]}}
