import{useEffect,useState}from'react';import{Avatar}from'../avatar/components/Avatar';import{ChefCinnamon}from'../characters/chef-cinnamon/components/ChefCinnamon';import{KingdomMap}from'../kingdom/map/KingdomMap';import{newPlayer,type AvatarConfig,type PlayerProfile}from'../profiles/types';import{purchaseItem,equipItem}from'../rewards/store';import{Shop}from'../shop/Shop';import{playerRepository}from'../storage/playerRepository';
const defaults:AvatarConfig={skinTone:'warm',hairStyle:'curls',hairColor:'#5a3424',outfit:'#6d3b8c',glasses:false};type Screen='home'|'map'|'shop';
export function App(){const[players,setPlayers]=useState<PlayerProfile[]>([]);const[active,setActive]=useState<PlayerProfile>();const[creating,setCreating]=useState(false);const[screen,setScreen]=useState<Screen>('home');const[name,setName]=useState('');const[avatar,setAvatar]=useState(defaults);const[notice,setNotice]=useState('');useEffect(()=>{playerRepository.list().then(setPlayers)},[]);
async function persist(player:PlayerProfile){await playerRepository.save(player);setActive(player);setPlayers(all=>all.map(x=>x.id===player.id?player:x))}
async function create(){if(!name.trim())return;const p=newPlayer(name,avatar);await playerRepository.save(p);setPlayers(x=>[...x,p]);setActive(p);speak(p.firstName)}
function speak(firstName:string){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(`Hello, ${firstName}!`))}}
async function buy(itemId:string){if(!active)return;const result=purchaseItem(active,itemId);if(!result.ok){setNotice(result.reason==='owned'?'You already own that item.':'Keep reading to earn more stars.');return}await persist(result.player);setNotice('Purchase saved to this player’s inventory.')}
async function equip(itemId:string){if(active)await persist(equipItem(active,itemId))}
if(active)return <main className={active.accessibility.reduceMotion?'reduce-motion':''}><header><button onClick={()=>{setActive(undefined);setScreen('home')}}>Switch reader</button><nav aria-label="Main navigation"><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}>Home</button><button className={screen==='map'?'active':''} onClick={()=>setScreen('map')}>Kingdom map</button><button className={screen==='shop'?'active':''} onClick={()=>setScreen('shop')}>Star Shop</button></nav><span className="stars" aria-label={`${active.stars} stars`}>Stars: {active.stars}</span></header>{notice&&<p className="toast" role="status">{notice}</p>}{screen==='map'?<KingdomMap player={active}/>:screen==='shop'?<Shop player={active} onBuy={buy} onEquip={equip}/>:<section className="home"><div><ChefCinnamon state="wave"/><div className="speech"><strong>Hello, {active.firstName}!</strong><br/>Cookie Kingdom is happy to see you.</div></div><Avatar config={active.avatar}/><h1>Your next reading mission is ready.</h1><button className="primary" onClick={()=>setScreen('map')}>Explore the kingdom map</button><button onClick={()=>setScreen('shop')}>Visit the Star Shop</button></section>}</main>;
if(creating)return <main><section className="panel creator"><h1>Create a reader</h1><label>First name<input value={name} onChange={e=>setName(e.target.value)} maxLength={24}/></label><Avatar config={avatar}/><fieldset><legend>Skin tone</legend>{(['light','warm','deep']as const).map(x=><button key={x} className={avatar.skinTone===x?'selected':''} onClick={()=>setAvatar({...avatar,skinTone:x})}>{x}</button>)}</fieldset><fieldset><legend>Hair</legend>{(['curls','waves','short']as const).map(x=><button key={x} className={avatar.hairStyle===x?'selected':''} onClick={()=>setAvatar({...avatar,hairStyle:x})}>{x}</button>)}</fieldset><label><input type="checkbox" checked={avatar.glasses} onChange={e=>setAvatar({...avatar,glasses:e.target.checked})}/> Glasses</label><button className="primary" onClick={create}>Start with 150 stars</button><button onClick={()=>setCreating(false)}>Back</button></section></main>;
return <main><section className="panel picker"><ChefCinnamon/><h1>Who is reading today?</h1><div className="profile-grid">{players.map(p=><button key={p.id} className="profile-card" onClick={()=>{setActive(p);speak(p.firstName)}}><Avatar config={p.avatar}/><strong>{p.firstName}</strong><span>Stars: {p.stars}</span></button>)}</div><button className="primary" onClick={()=>setCreating(true)}>Create a new player</button><button className="parent">Parent area</button></section></main>}
