import{useState}from'react';import type{ActivityScore,LessonActivity}from'../types';
const tokenize=(value:string):string[]=>Array.from(value.toLowerCase().match(/[a-z']+/g)??[]);
export function scoreActivity(activity:LessonActivity,response:unknown):ActivityScore{let score=0;if(activity.answer!==undefined)score=Number(response===activity.answer);else if(activity.correctOrder)score=Number(JSON.stringify(response)===JSON.stringify(activity.correctOrder));else if(activity.pairs)score=Number(JSON.stringify(response)===JSON.stringify(activity.pairs));else if(typeof response==='string'){const words=tokenize(response),accepted: string[]=activity.acceptedText??[];score=accepted.length?accepted.filter(x=>words.includes(x.toLowerCase())).length/accepted.length:Number(words.length>=3)}return{activityId:activity.id,score,correct:score>=.75,response,skillEvidence:[activity.type]}}
export function ActivityPlayer({activity,saved,onProgress,onComplete}:{activity:LessonActivity;saved?:unknown;onProgress:(value:unknown)=>void;onComplete:(score:ActivityScore)=>void}){const initial=activity.correctOrder??activity.options??[],[order,setOrder]=useState<string[]>(Array.isArray(saved)?saved as string[]:initial),[text,setText]=useState(typeof saved==='string'?saved:''),[selected,setSelected]=useState<number>(),[matches,setMatches]=useState<Record<string,string>>({});const move=(index:number,delta:number)=>{const target=index+delta;if(target<0||target>=order.length)return;const copy=[...order];[copy[index],copy[target]]=[copy[target],copy[index]];setOrder(copy);onProgress(copy)};
if(activity.type==='vocabulary'&&activity.vocabulary)return <section className="vocabulary-warmup" aria-label={`Vocabulary: ${activity.vocabulary.word}`}><h3>{activity.vocabulary.word}</h3><p><strong>Pronunciation:</strong> {activity.vocabulary.pronunciation}</p><p><strong>Syllables:</strong> {activity.vocabulary.syllables.join(' · ')}</p><p>{activity.vocabulary.definition}</p><p><em>{activity.vocabulary.example}</em></p>{activity.vocabulary.visualCue&&<p aria-label="Visual cue">{activity.vocabulary.visualCue}</p>}<button onClick={()=>onComplete(scoreActivity(activity,activity.answer??0))}>I’m ready</button></section>;
if(activity.type==='matching'&&activity.pairs){const response=activity.pairs.map(([left])=>[left,matches[left]]);return <section aria-label={activity.prompt}><h3>{activity.prompt}</h3>{activity.pairs.map(([left])=><label key={left}>{left}<select aria-label={`Match for ${left}`} value={matches[left]??''} onChange={e=>{const next={...matches,[left]:e.target.value};setMatches(next);onProgress(next)}}><option value="">Choose a match</option>{activity.pairs!.map(([,right])=><option key={right}>{right}</option>)}</select></label>)}<button disabled={Object.keys(matches).length<activity.pairs.length} onClick={()=>onComplete(scoreActivity(activity,response))}>Check matches</button></section>}
if(activity.type==='drag-order'||activity.type==='sentence-building')return <section aria-label={activity.prompt}><h3>{activity.prompt}</h3><ol className="order-list">{order.map((item,i)=><li key={`${item}-${i}`} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=Number(e.dataTransfer.getData('text/plain'));move(from,i-from)}} tabIndex={0} aria-label={`${item}, position ${i+1}`}><span>{item}</span><button aria-label={`Move ${item} earlier`} disabled={!i} onClick={()=>move(i,-1)}>↑</button><button aria-label={`Move ${item} later`} disabled={i===order.length-1} onClick={()=>move(i,1)}>↓</button></li>)}</ol><button onClick={()=>onComplete(scoreActivity(activity,order))}>Check order</button></section>;
if(['short-response','retelling','syllable-breakdown','morphology'].includes(activity.type))return <section><h3>{activity.prompt}</h3><textarea aria-label="Your response" value={text} onChange={e=>{setText(e.target.value);onProgress(e.target.value)}}/><button disabled={!text.trim()} onClick={()=>onComplete(scoreActivity(activity,text))}>Submit response</button></section>;
return <section><h3>{activity.prompt}</h3>{activity.options?.map((x,i)=><button key={x} aria-pressed={selected===i} onClick={()=>{setSelected(i);onProgress(i)}}>{x}</button>)}<button disabled={selected===undefined} onClick={()=>onComplete(scoreActivity(activity,selected))}>Check answer</button></section>}
