import{useState}from'react';
import type{ActivityScore,LessonActivity}from'../types';

type Props={activity:LessonActivity;saved?:unknown;reduceMotion?:boolean;onProgress:(value:unknown)=>void;onComplete:(score:ActivityScore)=>void};
const result=(a:LessonActivity,response:unknown,correct:boolean,attempts=1):ActivityScore=>({activityId:a.id,response,correct,score:correct?1:0,skillEvidence:[a.type],attempts});

export function DragAndDropSort({activity,saved,onProgress,onComplete}:Props){const initial=Array.isArray(saved)?saved as string[]:activity.options??[],[items,setItems]=useState(initial),[attempts,setAttempts]=useState(0);function move(from:number,to:number){if(from===to||to<0||to>=items.length)return;const next=[...items],[item]=next.splice(from,1);next.splice(to,0,item);setItems(next);onProgress(next)}function check(){const ok=JSON.stringify(items)===JSON.stringify(activity.correctOrder);setAttempts(x=>x+1);if(ok)onComplete(result(activity,items,true,attempts+1))}return <section className="interaction-card" aria-label={activity.prompt}><h2>{activity.prompt}</h2><p className="interaction-help">Drag large cards, or use the arrow controls.</p><ol className="movable-list">{items.map((item,i)=><li key={item} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData('text/plain')),i)}><span className="story-card" tabIndex={0}>{item}</span><button aria-label={`Move ${item} earlier`} disabled={!i} onClick={()=>move(i,i-1)}>Move up</button><button aria-label={`Move ${item} later`} disabled={i===items.length-1} onClick={()=>move(i,i+1)}>Move down</button></li>)}</ol>{attempts>0&&<p role="status" className="gentle-retry">Almost there—look back at the passage. The pieces stayed ready for another try.</p>}<button className="primary" onClick={check}>Lock pieces in place</button></section>}
export const SequenceBuilder=DragAndDropSort;export const WordTileSentenceBuilder=DragAndDropSort;export const StoryCardRetell=DragAndDropSort;export const MapRepairInteraction=DragAndDropSort;

export function MatchingPairs({activity,saved,onProgress,onComplete}:Props){const[matches,setMatches]=useState<Record<string,string>>((saved&&typeof saved==='object'?saved:{})as Record<string,string>),[retry,setRetry]=useState(false);const pairs=activity.pairs??[];function check(){const ok=pairs.every(([l,r])=>matches[l]===r);if(ok)onComplete(result(activity,matches,true));else setRetry(true)}return <section className="interaction-card" aria-label={activity.prompt}><h2>{activity.prompt}</h2><div className="matching-board">{pairs.map(([left])=><label key={left}><strong>{left}</strong><select aria-label={`Match for ${left}`} value={matches[left]??''} onChange={e=>{const next={...matches,[left]:e.target.value};setMatches(next);onProgress(next)}}><option value="">Choose a large picture card</option>{pairs.map(([,right])=><option key={right}>{right}</option>)}</select></label>)}</div>{retry&&<p role="status" className="gentle-retry">One match drifted back. Chef Cinnamon made the correct target glow.</p>}<button className="primary" disabled={Object.keys(matches).length<pairs.length} onClick={check}>Join the matching cards</button></section>}

export function EvidenceHighlighter({activity,saved,onProgress,onComplete}:Props){const[selected,setSelected]=useState<number|undefined>(typeof saved==='number'?saved:undefined),[retry,setRetry]=useState(false);return <section className="interaction-card evidence-board"><h2>{activity.prompt}</h2><p>Tap the evidence directly in the passage.</p>{activity.options?.map((sentence,i)=><button key={sentence} className="evidence-sentence" aria-pressed={selected===i} onClick={()=>{setSelected(i);onProgress(i)}}>{sentence}</button>)}{retry&&<p role="status" className="gentle-retry">Look back at the clue sentence Chef Cinnamon is pointing toward.</p>}<button className="primary" disabled={selected===undefined} onClick={()=>selected===activity.answer?onComplete(result(activity,selected,true)):setRetry(true)}>Use this evidence</button></section>}

export function InteractiveSceneHotspots({activity,saved,onProgress,onComplete}:Props){const[found,setFound]=useState<string[]>(Array.isArray(saved)?saved as string[]:[]),[message,setMessage]=useState('Explore each large object.');function choose(id:string){const spot=activity.hotspots?.find(x=>x.id===id);if(!spot)return;const next=[...new Set([...found,id])];setFound(next);onProgress(next);setMessage(spot.clue);if(spot.correct)onComplete(result(activity,id,true))}return <section className="interaction-card"><h2>{activity.prompt}</h2><div className="mission-scene" role="group" aria-label="Interactive illustrated meadow scene"><svg viewBox="0 0 600 280" aria-hidden="true"><path d="M0 195Q120 130 245 190T600 145V280H0Z" fill="#8bd56c"/><path d="M0 220Q180 170 330 230T600 190" fill="none" stroke="#71bde8" strokeWidth="42"/><circle cx="480" cy="76" r="44" fill="#ffe778"/><path d="M110 180h140v45H110z" fill="#f7d4ea"/><path d="M365 115l25 82h-50z" fill="#f3c940"/></svg>{activity.hotspots?.map((spot,i)=><button key={spot.id} className={`hotspot hotspot-${i+1}`} aria-label={`Explore ${spot.label}`} onClick={()=>choose(spot.id)}>{spot.label}</button>)}</div><p role="status">{message}</p></section>}

export function RecipeIngredientDrop(props:Props){return <div className="recipe-board"><div className="svg-bowl" role="img" aria-label="Rainbow mixing bowl"><svg viewBox="0 0 200 110"><path d="M20 25h160q-12 72-80 72T20 25Z" fill="#9d72cf"/><path d="M35 29h130" stroke="#fff" strokeWidth="8"/></svg></div><DragAndDropSort {...props}/></div>}

export function StirringGesture({activity,saved,onProgress,onComplete}:Props){const[count,setCount]=useState(typeof saved==='number'?saved:0);function stir(){const next=count+1;setCount(next);onProgress(next);if(next>=4)onComplete(result(activity,next,true))}return <section className="interaction-card"><h2>{activity.prompt}</h2><button className="stirring-bowl" aria-label="Stir rainbow bowl; press four times or move pointer across it" onPointerMove={e=>{if(e.buttons)stir()}} onClick={stir}><span className="stirring-spoon">Mix</span></button><p aria-live="polite">{Math.min(count,4)} of 4 gentle stirs</p><button onClick={stir}>Keyboard stirring step</button></section>}

export function PathChoice({activity,onProgress,onComplete}:Props){const[retry,setRetry]=useState(false);return <section className="interaction-card"><h2>{activity.prompt}</h2><div className="path-board">{activity.options?.map((path,i)=><button key={path} className="path-sign" onClick={()=>{onProgress(i);if(i===activity.answer)onComplete(result(activity,i,true));else setRetry(true)}}>{path}</button>)}</div>{retry&&<p role="status" className="gentle-retry">That path curls back gently. The clue’s direction word is glowing.</p>}</section>}

export function SoundPatternSort({activity,saved,onProgress,onComplete}:Props){const[categorized,setCategorized]=useState<Record<string,string[]>>((saved&&typeof saved==='object'?saved:{})as Record<string,string[]>);const categories=Object.keys(activity.categories??{}),words=activity.options??[];function place(word:string,category:string){const next=Object.fromEntries(categories.map(c=>[c,(categorized[c]??[]).filter(x=>x!==word)]));next[category]=[...(next[category]??[]),word];setCategorized(next);onProgress(next)}function check(){const ok=categories.every(c=>JSON.stringify([...(categorized[c]??[])].sort())===JSON.stringify([...(activity.categories?.[c]??[])].sort()));if(ok)onComplete(result(activity,categorized,true))}return <section className="interaction-card"><h2>{activity.prompt}</h2>{words.map(word=><label key={word}>{word}<select aria-label={`Sound group for ${word}`} value={categories.find(c=>categorized[c]?.includes(word))??''} onChange={e=>place(word,e.target.value)}><option value="">Choose sound basket</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label>)}<button className="primary" onClick={check}>Unlock sound code</button></section>}

export function VocabularyRevealCard({activity,onComplete}:Props){const[open,setOpen]=useState(false),v=activity.vocabulary!;return <section className="interaction-card vocabulary-card"><h2>{activity.prompt}</h2><button aria-expanded={open} onClick={()=>setOpen(true)}>Reveal {v.word}</button>{open&&<div><strong>{v.word}</strong><p>{v.syllables.join(' · ')} · {v.pronunciation}</p><p>{v.definition}</p><p><em>{v.example}</em></p><button className="primary" onClick={()=>onComplete(result(activity,v.word,true))}>Give this clue to Pip</button></div>}</section>}

export function ColorRestorationInteraction(props:Props){return <div className="color-restoration"><MatchingPairs {...props}/></div>}
export function TreasureChestReward({activity,onComplete}:Props){const[open,setOpen]=useState(false);return <section className="interaction-card treasure-stage"><h2>{activity.prompt}</h2><button className={`treasure-chest ${open?'open':''}`} aria-label="Open restored treasure chest" onClick={()=>{setOpen(true);onComplete(result(activity,'opened',true))}}><svg viewBox="0 0 180 140"><path d="M25 58Q25 18 90 18t65 40" fill="#f6c35b" stroke="#704820" strokeWidth="8"/><path d="M20 58h140v65H20z" fill="#b87935" stroke="#704820" strokeWidth="8"/><circle cx="90" cy="82" r="12" fill="#fff3a5"/></svg></button><p aria-live="polite">{open?'Stars swirl into your adventure pouch!':'The chest is ready.'}</p></section>}
