import{fireEvent,render,screen}from'@testing-library/react';import{describe,expect,it,vi}from'vitest';import{DragAndDropSort,EvidenceHighlighter,InteractiveSceneHotspots,MatchingPairs,RecipeIngredientDrop,SoundPatternSort,StirringGesture,WordTileSentenceBuilder}from'./InteractiveActivities';import type{LessonActivity}from'../types';
const base=(extra:Partial<LessonActivity>):LessonActivity=>({id:'a',type:'drag-order',prompt:'Move the story pieces',...extra});
const props=(activity:LessonActivity,saved?:unknown)=>({activity,saved,onProgress:vi.fn(),onComplete:vi.fn()});
describe('world manipulation activities',()=>{
 it('supports pointer drag-and-drop sorting with typed scoring',()=>{const p=props(base({correctOrder:['one','two'],options:['two','one']}));render(<DragAndDropSort {...p}/>);const cards=screen.getAllByRole('listitem');const transfer={value:'',setData(_t:string,v:string){this.value=v},getData(){return this.value}};fireEvent.dragStart(cards[0],{dataTransfer:transfer});fireEvent.drop(cards[1],{dataTransfer:transfer});fireEvent.click(screen.getByText('Lock pieces in place'));expect(p.onComplete).toHaveBeenCalledWith(expect.objectContaining({correct:true,score:1,skillEvidence:['drag-order']}))});
 it('supports keyboard ordering and restores partial state',()=>{const p=props(base({type:'sentence-building',correctOrder:['We','read'],options:['read','We']}),['read','We']);render(<WordTileSentenceBuilder {...p}/>);fireEvent.click(screen.getByLabelText('Move read later'));expect(p.onProgress).toHaveBeenCalledWith(['We','read']);fireEvent.click(screen.getByText('Lock pieces in place'));expect(p.onComplete).toHaveBeenCalled()});
 it('matches vocabulary with screen-reader labels',()=>{const p=props(base({type:'matching',pairs:[['brook','water'],['oak','tree']]}));render(<MatchingPairs {...p}/>);fireEvent.change(screen.getByLabelText('Match for brook'),{target:{value:'water'}});fireEvent.change(screen.getByLabelText('Match for oak'),{target:{value:'tree'}});fireEvent.click(screen.getByText('Join the matching cards'));expect(p.onComplete).toHaveBeenCalled()});
 it('highlights evidence and gives a gentle retry',()=>{const p=props(base({type:'story-evidence',options:['wrong sentence','proof sentence'],answer:1}));render(<EvidenceHighlighter {...p}/>);fireEvent.click(screen.getByText('wrong sentence'));fireEvent.click(screen.getByText('Use this evidence'));expect(screen.getByRole('status')).toHaveTextContent('Look back');fireEvent.click(screen.getByText('proof sentence'));fireEvent.click(screen.getByText('Use this evidence'));expect(p.onComplete).toHaveBeenCalled()});
 it('lets a child explore scene hotspots with large named targets',()=>{const p=props(base({type:'scene-hotspots',hotspots:[{id:'log',label:'hollow log',clue:'A beetle.'},{id:'cloth',label:'striped cloth',clue:'Found it!',correct:true}]}));render(<InteractiveSceneHotspots {...p}/>);fireEvent.click(screen.getByLabelText('Explore hollow log'));expect(screen.getByRole('status')).toHaveTextContent('beetle');fireEvent.click(screen.getByLabelText('Explore striped cloth'));expect(p.onComplete).toHaveBeenCalled()});
 it('checks recipe ingredient order using pointer-sized cards',()=>{const p=props(base({type:'recipe-drop',correctOrder:['juice','sugar'],options:['sugar','juice']}));render(<RecipeIngredientDrop {...p}/>);fireEvent.click(screen.getByLabelText('Move sugar later'));fireEvent.click(screen.getByText('Lock pieces in place'));expect(p.onComplete).toHaveBeenCalled()});
 it('offers a keyboard fallback for the stirring gesture',()=>{const p=props(base({type:'stirring'}));render(<StirringGesture {...p}/>);for(let i=0;i<4;i++)fireEvent.click(screen.getByText('Keyboard stirring step'));expect(p.onComplete).toHaveBeenCalledWith(expect.objectContaining({correct:true}))});
 it('sorts sound patterns without precise motor control',()=>{const p=props(base({type:'sound-sort',categories:{br:['brook'],st:['stone']},options:['brook','stone']}));render(<SoundPatternSort {...p}/>);fireEvent.change(screen.getByLabelText('Sound group for brook'),{target:{value:'br'}});fireEvent.change(screen.getByLabelText('Sound group for stone'),{target:{value:'st'}});fireEvent.click(screen.getByText('Unlock sound code'));expect(p.onComplete).toHaveBeenCalled()});
});
