export type ActivityType='read-aloud'|'word-recognition'|'sequencing'|'main-idea'|'retelling'|'vocabulary'|'sentence-building'|'story-evidence'|'short-response'|'drag-order'|'matching'|'syllable-breakdown'|'morphology'|'listen-then-read'|'scene-hotspots'|'recipe-drop'|'stirring'|'path-choice'|'story-card-retell'|'sound-sort'|'map-repair'|'color-restoration'|'treasure-reward';
export interface VocabularyCard{word:string;pronunciation:string;syllables:string[];definition:string;example:string;visualCue?:string}
export interface SceneHotspot{id:string;label:string;clue:string;correct?:boolean}
export interface LessonActivity{id:string;type:ActivityType;prompt:string;instruction?:string;options?:string[];answer?:number;acceptedText?:string[];correctOrder?:string[];pairs?:Array<[string,string]>;vocabulary?:VocabularyCard;hotspots?:SceneHotspot[];categories?:Record<string,string[]>;worldChange?:string}
export interface ActivityScore{activityId:string;score:number;correct:boolean;response:unknown;skillEvidence:string[];attempts?:number}
export type MissionKind='lesson'|'review'|'villain'|'checkpoint';
export interface Lesson{id:string;regionId:number;kind:MissionKind;title:string;mission:string;scene:'meadow'|'bird'|'bridge'|'bakery'|'trail'|'map'|'gate';passage:string;activities:LessonActivity[];rewardStars:number;skills:string[]}
export interface LessonAttempt{lessonId:string;score:number;passed:boolean;completedAt:string;skills:string[]}
export interface MasteryRecord{attempts:LessonAttempt[];masteredSkills:string[];rewardedLessonIds:string[];villainDefeated:boolean;checkpointPassed:boolean}
